config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users
  resources :books
  resources :likes
  resources :comments
  resources :requests
  resources :relationships
  resources :likes
  namespace :admin do
  root "static_pages#home"
  resources :categories, except: :show
  resources :books
  resources :users
  resources :reviews, only: [:index, :show, :destroy, :edit]
  resources :requests
  resources :authors
  resources :publishers
  resources :charts
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  belongs_to :publisher

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :request_items, dependent: :destroy
  has_many :book_items, dependent: :destroy
  has_many :authors, through: :book_items

  ratyrate_rateable 'visual_effects', 'original_score'
  
  mount_uploader :image, ImageUploader

  accepts_nested_attributes_for :book_items
  accepts_nested_attributes_for :authors

  validates :title, presence: true, length: {maximum: Settings.maximum.name}
  validates :description, presence: true,
    length: {maximum: Settings.maximum.description}
  validates :category_id, presence: true
  validates :publisher_id, presence: true

  scope :book_order, -> {order "created_at desc"}

  scope :by_search_book, ->start_day, end_day do
    where "created_at >= '#{start_day}' AND created_at <= '#{end_day}'" if start_day.present? and end_day.present?
  end

  def group_by_book
    created_at.to_date.to_s(:db)
  end

  def get_author id
    @name = Author.find_by id: id
    if @name.nil?

    else
      @name.name
    end
  end

  def self.to_xls
    csv_data = CSV.generate do |csv|
      csv << [I18n.t("admin.books.index"), I18n.t("admin.books.book_title"), I18n.t("admin.books.category_name"),
        I18n.t("admin.books.author_name"), I18n.t("admin.books.publisher_name")]
      all.each do |book|
        csv << [book.id, book.title, book.category.name,
          book.publisher.name]
      end
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  include ApplicationHelper
  before_action :verify_admin
  before_action :load_all_categories, :load_all_authors, :load_all_publishers
  before_action :load_book, except: [:create, :index, :new]

  def index
    @q = Book.search params[:q]
    @book_all = @q.result(distinct: true)
    respond_to do |format|
      format.html {
        @books = @book_all.page(params[:page]).per Settings.per_page
      }
      format.xlsx {send_data @book_all.to_xls,
        filename: generate_file_name(t "admin.books.book_file_name")}
    end
  end

  def new
    @book = Book.new
    @book.authors.build
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = t ".book_add_success"
      redirect_back fallback_location: admin_books_path
    else
      render :new
    end
  end

  def destroy
    if @book.is_borrowed?
      flash[:warning] = t ".delete_book_borrowed"
    else
      if @book.destroy
        flash[:success] = t ".delete_success"
      else
        flash[:danger] = t ".delete_unsuccess"
      end
    end
    redirect_back fallback_location: admin_categories_path
  end

  def update
    if @book.update_attributes book_params
      flash[:success] = t ".edit_book"
      render :edit
    else
      flash[:danger] = t ".edit_failed"
      render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit :category_id, :title, :description, :author_id,
      :publisher_id, :name, authors_attributes: [:name, :description]
  end

  def load_all_categories
    @categories = Category.select "id, name"
  end

  def load_all_authors
    @authors = Author.select "id, name"
  end

  def load_all_publishers
    @publishers = Publisher.select "id, name"
  end

  def load_book
    @book = Book.find_by id: params[:id]
    render_404 unless @book
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include ApplicationHelper
  before_action :load_all_categories, :load_all_authors, :load_all_publishers
  before_action :load_book, except: [:create, :index, :new]

  def index
    @q = Book.search params[:q]
    @books = @q.result(distinct: true).page(params[:page]).per Settings.per_page
  end

  def show
  end

  private
  def load_all_categories
    @categories = Category.select "id, name"
  end

  def load_all_authors
    @authors = Author.select "id, name"
  end

  def load_all_publishers
    @publishers = Publisher.select "id, name"
  end

  def load_book
    @book = Book.find_by id: params[:id]
    render_404 unless @book
  end
end

app/views/admin/books/_book.html.erb
<tr>
  <td><%= book.id %></td>
  <td><%= image_tag book.image.url, size: Settings.size_image_avater %></td>
  <td><%= link_to book.title, admin_book_path(book) %></td>
  <td><%= book.category.name %></td>
  <td><%= get_author book.id %></td>
  <td><%= book.publisher.name %></td>
  <td>
    <%= link_to edit_admin_book_path book do %>
      <span class="btn glyphicon glyphicon-pencil btn-info"> </span>
    <% end %>
    <%= link_to [:admin, book], method: :delete, data: {confirm: t("delete.confirm")} do %>
      <span class="btn glyphicon glyphicon-remove btn-danger "> </span>
    <% end %>
  </td>
</tr>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>

   <%= f.fields_for :authors do |builder| %>
          <%= render "admin/shared/author_fields", f: builder %>
  <% end %>

  <p><%= link_to_add_fields "Add author", f, :authors %></p>

  <%= f.label :category %>
  <%= f.select :category_id, options_for_select(
    @categories.collect{|category|["#{category.name}", category.id]},
    {class: "form-control"}) %>
  <br>
  <%= f.label :publisher %>
  <%= f.select :publisher_id, options_for_select(
    @publishers.collect{|publisher|["#{publisher.name}", publisher.id]},
    {class: "form-control"}) %>
  <br>
  <%= f.submit t("admin.books.add_book"), class: "btn btn-success" %>
<% end %>

app/views/admin/books/edit.html.erb
<% provide :title, t("admin.books.edit_book") %>
<h1><% t "edit_book" %></h1>

<div class="row">
  <div class="col-md-9">
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/index.html.erb
<% provide :title, t("admin.books.book_list") %>
<h1><%= t "admin.books.book_list" %></h1>
<div class="row">
  <%= search_form_for [:admin, @q] do |f| %>
    <div class="col-md-3">
      <%= f.text_field :title_cont, placeholder: t("admin.books.search"),
        class: "form-control search-field", autofocus: true %>
    </div>
    <div class="col-md-1">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </span>
    </div>
    <div class="col-md-1">
      <%= f.select :category_id_start,
        options_for_select(@categories.map{|c| [c.name, c.id]}),
        class: "form-control", include_blank: t("all_categories")
      %>
    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-1">
      <%= f.select :publisher_id_start,
        options_for_select(@publishers.map{|c| [c.name, c.id]}),
        class: "form-control", include_blank: t("all_publishers") %>
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-1">
      <%= f.select :id_start,
        options_for_select(@authors.map{|c| [c.name, c.id]}),
        class: "form-control", include_blank: t("all_authors") %>
    </div>
  <% end %>
</div>
<%= link_to t("excel"), params.except(:host, :port, :protocol).permit!.
  merge(format: "xlsx") %>
<div class="table-responsive">
  <table class="table well">
    <thead>
      <tr>
        <th><%= t "index" %></th>
        <th><%= t "image" %></th>
        <th><%= t "book_title" %></th>
        <th><%= t "category" %></th>
        <th><%= t "author_name" %></th>
        <th><%= t "publisher_name" %></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @books %>
    </tbody>
  </table>
</div>
<%= paginate @books, theme: "twitter-bootstrap-3" %>

app/views/admin/books/new.html.erb
<% provide :title, t("admin.books.add_book") %>
<h1><% t "admin.books.add_book" %></h1>
<div class="row">
  <div class="col-md-6">
    <%= render "form" %>
  </div>
</div>