config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users
  resources :books
  resources :likes
  resources :comments
  resources :requests
  resources :relationships
  resources :likes
  namespace :admin do
  root "static_pages#home"
  resources :categories, except: :show
  resources :books
  resources :users
  resources :reviews, only: [:index, :show, :destroy, :edit]
  resources :requests
  resources :authors
  resources :publishers
  resources :charts
  end
end

app/controllers/admin/charts_controller.rb
class Admin::ChartsController < ApplicationController
  include ApplicationHelper
  def index
    @user = User.by_search_user params[:start_day], params[:end_day]
    @user_array = @user.group_by(&:group_by_user).map {|k,v| [k, v.length]}.sort
    @book = Book.by_search_book params[:start_day], params[:end_day]
    @book_array = @book.group_by(&:group_by_book).map {|k,v| [k, v.length]}.sort
  end
end

app/views/admin/charts/index.html.erb
<div class="container-fluid">
  <div class="margin_top"><%= t ".today" %> : <%= Time.now.strftime(Settings.date_format) %></div>
    <div class="col-sm-4">
      <%= form_tag admin_charts_path, class: "form-horizontal bucket-form margin_top", method: "get" do %>
        <div class="form-group">
          <div class="input-group date" id="datetimepicker">
            <%= text_field_tag :start_day, params[:start_day], placeholder: "start day",
              class: 'form-control', data: { date_format: 'YYYY/MM/DD' } %>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
          </div>
          <div class="input-group date" id="datetimepicker1">
            <%= text_field_tag :end_day, params[:end_day], placeholder: "end day",
              class: 'form-control', data: { date_format: 'YYYY/MM/DD' } %>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
          </div>
        </div>
        <%= submit_tag "Search", start_day: nil, end_day: nil, class: "btn-info btn" %>
    <% end %>
  </div>
  <div class=" col-md-8 col-md-offset-5 margin_top"> <h6>Data Users </h6> </div>
  <div class="margin_tops"> <%= column_chart @user_array %> </div>
  <div class="hight_center"> </div>
  <div class=" col-md-8 col-md-offset-5 margin_top"> <h6>Data Books </h6> </div>
  <div class="margin_tops"> <%= column_chart @book_array %> </div>
</div>