config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users
  resources :books
  resources :likes
  resources :comments
  resources :requests
  resources :relationships
  resources :likes
  namespace :admin do
  root "static_pages#home"
  resources :categories, except: :show
  resources :books
  resources :users
  resources :reviews, only: [:index, :show, :destroy, :edit]
  resources :requests
  resources :authors
  resources :publishers
  resources :charts
  end
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true, length: {maximum: Settings.maximum.name}
  validates :address, presence: true, length: {maximum: Settings.maximum.address}
  validates :email, presence: true, length: {maximum: Settings.maximum.email}
  validates :phone, presence: true, length: {maximum: Settings.maximum.phone}
  validates :description, presence: true, length: {maximum:
    Settings.maximum.description}

  scope :all_except, ->user {where.not id: user}

  def self.to_xls
    CSV.generate do |csv|
      csv << [I18n.t("admin.publishers.index"), I18n.t("admin.publishers.name"),
        I18n.t("admin.publishers.description"), I18n.t("admin.publishers.quantity")]
      all.each do |publisher|
        csv << [publisher.id, publisher.name, publisher.description]
      end
    end
  end
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < ApplicationController
  include ApplicationHelper
  before_action :verify_admin
  before_action :load_publisher, except: [:create, :index, :new]

  def index
    @q = Publisher.search params[:q]
    @publisher_all = @q.result(distinct: true)
    respond_to do |format|
      format.html {
        @publishers = @publisher_all.page(params[:page]).per Settings.per_page
      }
      format.xlsx {send_data @publisher_all.to_xls,
        filename: generate_file_name(t ".publishers_file_name")}
      end
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new publisher_params
    if @publisher.save
      flash[:success] = t "publisher_add_success"
      redirect_back fallback_location: admin_publishers_path
    else
      render :new
    end
  end

  def update
    if @publisher.update_attributes publisher_params
      flash[:success] = t ".edit_publisher"
      render :edit
    else
      render :edit
    end
  end

  def destroy
    if @publisher.destroy
      flash[:success] = t "delete_success"
    else
      flash[:danger] = t "delete_unsuccess"
    end
    redirect_back fallback_location: admin_publishers_path
  end

  private
  def publisher_params
    params.require(:publisher).permit :name, :email, :address, :phone_number,
      :description, :image
  end

  def load_publisher
    @publisher = Publisher.find_by id: params[:id]
    render_404 unless @publisher
  end

end

app/views/admin/publishers/_form.html.erb
<%= form_for [:admin, @publisher] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %>

  <%= f.label :phone %>
  <%= f.text_field :phone, class: "form-control" %>

  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.submit t("admin.publishers.add_publisher"), class: "btn btn-success" %>
<% end %>

app/views/admin/publishers/_publisher.html.erb
<tr>
  <td><%= publisher.id %></td>
  <td><%= publisher.name %></td>
  <td><%= publisher.description %></td>
  <td><%= publisher.email %></td>
  <td>
    <%= link_to edit_admin_publisher_path publisher do %>
      <span class="glyphicon glyphicon-pencil btn btn-info"> </span>
    <% end %>
  </td>
  <td>
    <%= link_to [:admin, publisher], method: :delete, data: {confirm: t("delete.confirm")} do %>
      <span class="glyphicon glyphicon-remove btn btn-danger"> </span>
    <% end %>
  </td>
</tr>

app/views/admin/publishers/edit.html.erb
<% provide :title, t("admin.publishers.edit_publisher") %>
<h1><% t "admin.publishers.edit_publisher" %></h1>
<div class="row">
  <div class="col-md-9">
    <%= render "form" %>
  </div>
</div>

app/views/admin/publishers/index.html.erb
<% provide :title, t("admin.publishers.publisher_list") %>
<h1><%= t "admin.publishers.publisher_list" %></h1>
  <div class="container margin_top">
    <div class="row">
      <%= search_form_for [:admin, @q] do |f| %>
        <div class="col-xs-6 col-xs-offset-2">
          <div class="input-group">
            <input type="hidden" name="search_param" value="all" id="search_param">
            <%= f.text_field :name_or_email_cont,
              placeholder: t("admin.publishers.search_publisher"), class: "form-control" %>
            <span class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <span class="glyphicon glyphicon-search"></span>
              </button>
            </span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<%= link_to t("excel"), params.except(:host, :port, :protocol).permit!.
  merge(format: "xlsx") %>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th><%= t "admin.publishers.index" %></th>
        <th><%= t "admin.publishers.publisher_name" %></th>
        <th><%= t "admin.publishers.address" %></th>
        <th><%= t "admin.publishers.email" %>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @publishers %>
    </tbody>
  </table>
  </div>
<%= paginate @publishers, theme: "twitter-bootstrap-3" %>

app/views/admin/publishers/new.html.erb
<% provide :title, t("admin.publishers.add_publisher") %>
<h1><%= t "admin.publishers.add_publisher" %></h1>
<div class="row">
  <div class="col-md-6">
    <%= render "form" %>
  </div>
</div>