config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users
  resources :books
  resources :likes
  resources :comments
  resources :requests
  resources :relationships
  resources :likes
  namespace :admin do
  root "static_pages#home"
  resources :categories, except: :show
  resources :books
  resources :users
  resources :reviews, only: [:index, :show, :destroy, :edit]
  resources :requests
  resources :authors
  resources :publishers
  resources :charts
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :book_items, dependent: :destroy
  has_many :books, dependent: :destroy
  validates :name, presence: true, length: {maximum: Settings.maximum.name}
  validates :description, presence: true,
    length: {maximum: Settings.maximum.description}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!
  before_action :verify_admin
  before_action :load_category, except: [:create, :index, :new]

  def index
    @q = Author.search params[:q]
    @categories_all = @q.result(distinct: true)
    respond_to do |format|
      format.html {
        @categories = @categories_all.page(params[:page]).per Settings.per_page
      }
      format.xlsx {send_data @categories_all.to_xls,
        filename: generate_file_name(t ".categories_file_name")}
    end
  end

  def new
    @category = Category.new
  end

  def show
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t ".category_add_success"
      redirect_back fallback_location: admin_categories_path
    else
      render :new
    end
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".edit_category"
      render :edit
    else
      flash[:danger] = t ".edit_failed"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".delete_unsuccess"
    end
    redirect_back fallback_location: admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name, :description
  end

  def load_category
    @category = Category.find_by id: params[:id]
    render_404 unless @category
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= index_for category_counter, @categories.current_page,
    Settings.item_per_page %></td>
  <td><%= link_to category.name, admin_category_path(category) %></td>
  <td><%= category.description %></td>
  <td><%= category.books.length %></td>
  <td>
    <%= link_to edit_admin_category_path category do %>
      <%= fa_icon "pencil" %>
    <% end %>
    <%= link_to [:admin, category], method: :delete, data: {confirm: t("delete.confirm")} do %>
        <%= fa_icon "trash-o" %>
    <% end %>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>


  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.submit t("admin.categories.create_category"), class: "btn btn-success" %>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, t("edit_category") %>
<h1><% t "edit_category" %></h1>

<div class="row">
  <div class="col-md-9">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t("admin.categories.categories_list") %>
<h1><%= t "admin.categories.categories_list" %></h1>
<div class="container margin_top">
  <div class="row">
    <%= search_form_for [:admin, @q] do |f| %>
      <div class="col-xs-6 col-xs-offset-2">
        <div class="input-group">
          <input type="hidden" name="search_param" value="all" id="search_param">
          <%= f.text_field :name_cont, placeholder: t("admin.categories.search_catergory"),
            class: "form-control" %>
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to t("excel"), params.except(:host, :port, :protocol).permit!.
  merge(format: "xlsx") %>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th><%= t "admin.categories.index" %></th>
        <th><%= t "admin.categories.category_name" %></th>
        <th><%= t "admin.categories.description" %></th>
        <th><%= t "admin.categories.quantity" %>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @categories %>
    </tbody>
  </table>
</div>
<%= paginate @categories, theme: "twitter-bootstrap-3"%>

app/views/admin/categories/new.html.erb
<% provide :title, t("admin.categories.create_category") %>
<h1><% t "admin.categories.create_category" %></h1>

<div class="row">
  <div class="col-md-6">
    <%= render "form" %>
  </div>
</div>